import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

export default function Home() {
  const [day, setDay] = useState(false);

  return (
    <div>
      <Head>
        <title>Bitcoin Clock</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon-32x32.png' />
      </Head>

      <main className='my-0'>
        {day ? (
          <>
            <div className='relative h-full w-full overflow-hidden sm:hidden'>
              <Image
                src='/mobile/bg-image-daytime.jpg'
                alt=''
                layout='fill'
                objectFit='cover'
                quality={100}
              />
            </div>
            <div className='relative hidden h-full w-full overflow-hidden sm:flex md:hidden'>
              <Image
                src='/tablet/bg-image-daytime.jpg'
                alt=''
                layout='fill'
                objectFit='cover'
                quality={100}
              />
            </div>
            <div className='relative hidden h-screen w-full overflow-hidden md:flex'>
              <Image
                src='/desktop/bg-image-daytime.jpg'
                alt=''
                layout='fill'
                objectFit='cover'
                quality={100}
              />
            </div>
          </>
        ) : (
          <>
            <div className='relative h-full w-full overflow-hidden sm:hidden'>
              <Image
                src='/mobile/bg-image-nighttime.jpg'
                alt=''
                layout='fill'
                objectFit='cover'
                quality={100}
              />
            </div>
            <div className='relative hidden h-screen w-full sm:flex md:hidden'>
              <Image
                src='/tablet/bg-image-nighttime.jpg'
                alt=''
                layout='fill'
                objectFit='cover'
                quality={100}
              />
            </div>

            <div className='relative hidden h-screen w-full overflow-hidden md:flex'>
              <Image
                src='/desktop/bg-image-nighttime.jpg'
                alt=''
                layout='fill'
                objectFit='cover'
                quality={100}
              />
            </div>
          </>
        )}
      </main>

      <footer></footer>
    </div>
  );
}
